config/routes.rb
Rails.application.routes.draw do
  post "job_scraper/scrape", to: "job_scraper#scrape", as: :scrape_job
  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  resources :applications
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "applications#index"
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :require_authentication
  before_action :set_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json
  def index
    @applications = Current.user.applications
  end

  # GET /applications/1 or /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Current.user.applications.build(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to applications_path, notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy!

    respond_to do |format|
      format.html { redirect_to applications_path, status: :see_other, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.expect(application: [ :position, :company, :position_url, :description, :status ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_application.html.erb
<div id="<%= dom_id application %>" class="text-black">
  <div class="flex items-center justify-between">
    <p
      class="
        mt-0.5 whitespace-nowrap rounded-md bg-green-50 px-1.5 py-0.5 text-xs
        font-medium text-green-700 ring-1 ring-inset ring-green-600/20
      "
    >
      <%= application.status %>
    </p>

    <div class="relative flex-none" data-controller="menu">
      <button
        data-menu-target="button"
        data-action="click->menu#toggleMenu"
        id="options-menu-<%=application.id%>-button"
        type="button"
        class="-m-2.5 block p-2.5 text-gray-500 hover:text-gray-900"
        aria-expanded="false"
        aria-haspopup="true"
      >
        <span class="sr-only">Open options</span>
        <svg
          class="size-5"
          viewBox="0 0 20 20"
          fill="currentColor"
          aria-hidden="true"
          data-slot="icon"
        >
          <path
            d="M10 3a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM10 8.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM11.5 15.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z"
          />
        </svg>
      </button>
      <div
        data-menu-target="menu"
        class="
          transition opacity-0 scale-95 pointer-events-none absolute right-0 z-10 mt-2
          w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5
          focus:outline-none
        "
        role="menu"
        aria-orientation="vertical"
        aria-labelledby="options-menu-<%=application.id%>-button"
        tabindex="-1"
      >
        <%= link_to "Visit",
        application.position_url,
        {
          class: "block px-3 py-1 text-sm/6 text-gray-900",
          target: "_blank",
          rel: "noopener noreferrer",
        } %>
        <%= link_to "Edit",
        edit_application_path(application),
        class: "block px-3 py-1 text-sm/6 text-gray-900",
        role: "menuitem",
        id: "options-menu-#{application.id}-item-1",
        tabindex: "-1" %>
        <%= button_to "Delete",
        application,
        method: :delete,
        class: "block px-3 py-1 text-sm/6 text-gray-900",
        role: "menuitem",
        id: "options-menu-#{application.id}-item-2",
        tabindex: "-1" %>
      </div>
    </div>
  </div>
  <p class="whitespace-pre-line">
    <%= application.description %>
  </p>
</div>

app/views/applications/_form.html.erb
<turbo-frame id="application-form">
  <div data-controller="application-form">
    <%= form_with(model: application, class: "block", data: { turbo: false }) do |form| %>
      <% if application.errors.any? %>
        <div
          id="error_explanation"
          class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3"
        >
          <h2><%= pluralize(application.errors.count, "error") %>
            prohibited this application from being saved:</h2>

          <ul>
            <% application.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <input
        data-application-form-target="disabler"
        type="hidden"
        class="hidden peer"
      />
      <div
        class="
          isolate -space-y-px rounded-md shadow-sm mb-6 after:absolute relative
          after:inset-0 peer-disabled:after:animate-pulse
          peer-disabled:after:bg-gray-400/20 after:pointer-events-none
          peer-disabled:pointer-events-none
        "
      >
        <div
          class="
            relative rounded-md rounded-b-none px-3 pb-1.5 pt-2.5 ring-1 ring-inset
            ring-gray-300 focus-within:z-10 focus-within:ring-2 focus-within:ring-indigo-600
          "
        >
          <%= form.label :position_url,
                     class: "block text-xs font-medium text-gray-900 capitalize" %>
          <%= form.url_field :position_url,
                         data: {
                           "application-form-target": "url",
                           action: "input->application-form#showAIBtn:once",
                         },
                         class:
                           " block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6",
                         placeholder: "https://applify.com/careers/iasdJ123" %>
          <button
            data-application-form-target="aibtn"
            data-action="click->application-form#handleUrlInput"
            class="
              p-1 bg-gray-50 dark:bg-gray-900 hidden border rounded absolute right-1 bottom-1
              shadow-sm
            "
            title="Fill form with AI"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-4"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z"
              />
            </svg>
          </button>
        </div>
        <div
          class="
            relative px-3 pb-1.5 pt-2.5 ring-1 ring-inset ring-gray-300 focus-within:z-10
            focus-within:ring-2 focus-within:ring-indigo-600
          "
        >
          <%= form.label :position,
                     class: "block text-xs font-medium text-gray-900 capitalize" %>
          <%= form.text_field :position,
                          data: {
                            "application-form-target": "position",
                          },
                          class:
                            " block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6",
                          placeholder: "Founding Engineer" %>
        </div>
        <div
          class="
            relative px-3 pb-1.5 pt-2.5 ring-1 ring-inset ring-gray-300 focus-within:z-10
            focus-within:ring-2 focus-within:ring-indigo-600
          "
        >
          <%= form.label :company, class: "block text-xs font-medium text-gray-900 capitalize" %>
          <%= form.text_field :company,
                          data: {
                            "application-form-target": "company",
                          },
                          class:
                            " block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6",
                          placeholder: "SpaceX" %>
        </div>
        <div
          class="
            relative px-3 pb-1.5 pt-2.5 ring-1 ring-inset ring-gray-300 focus-within:z-10
            focus-within:ring-2 focus-within:ring-indigo-600
          "
        >
          <%= form.label :description,
                     class: "block text-xs font-medium text-gray-900 capitalize" %>
          <%= form.text_area :description,
                         rows: 10,
                         data: {
                           "application-form-target": "description",
                         },
                         class:
                           " block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6",
                         placeholder: "In this position..." %>
        </div>
        <div
          class="
            relative rounded-md rounded-t-none px-3 pb-1.5 pt-2.5 ring-1 ring-inset
            ring-gray-300 focus-within:z-10 focus-within:ring-2 focus-within:ring-indigo-600
          "
        >
          <%= form.label :status, class: "block text-xs font-medium text-gray-900 capitalize" %>
          <%= form.select :status,
                      [
                        %w[Pending pending],
                        ["Under Review", "under_review"],
                        ["Interview Scheduled", "interview_scheduled"],
                        %w[Interviewed interviewed],
                        ["Offer Extended", "offer_extended"],
                        ["Offer Accepted", "offer_accepted"],
                        ["Offer Declined", "offer_declined"],
                        %w[Rejected rejected],
                        %w[Withdrawn withdrawn],
                      ],
                      {},
                      {
                        class:
                          "block w-full border-0 p-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm/6",
                      } %>
        </div>
      </div>

      <div class="inline">
        <%= form.submit class:
                      "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:bg-gray-400 disabled:cursor-not-allowed",
                    data: {
                      "application-form-target": "submit",
                    } %>
      </div>
    <% end %>
  </div>
</turbo-frame>

app/views/applications/edit.html.erb
<% content_for :header do %>
  <div>
    <h1 class="text-3xl font-bold tracking-tight text-white"><%= @application.position %></h1>
    <p class="text-white/80"><%= @application.company %></p>
  </div>
  <div class="flex gap-4 items-center">
    <%= link_to "Back to applications",
    applications_path,
    class:
      "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-black" %>
  </div>
<% end %>

<% content_for :title do %>
  Applications |
  <%= @application.position %>
<% end %>

<div class="mx-auto w-full">
  <%= render "form", application: @application %>
</div>

app/views/applications/index.html.erb
<% content_for :header do %>
  <h1 class="text-3xl font-bold tracking-tight text-white">Applications</h1>
  <%= link_to new_application_path, { class: "rounded-full bg-indigo-600 p-2 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" } do %>

    <svg
      class="size-5"
      viewBox="0 0 20 20"
      fill="currentColor"
      aria-hidden="true"
      data-slot="icon"
    >
      <path
        d="M10.75 4.75a.75.75 0 0 0-1.5 0v4.5h-4.5a.75.75 0 0 0 0 1.5h4.5v4.5a.75.75 0 0 0 1.5 0v-4.5h4.5a.75.75 0 0 0 0-1.5h-4.5v-4.5Z"
      />
    </svg>
  <% end %>
<% end %>

<% content_for :title, "Applications" %>

<div class="w-full">
  <% if notice.present? %>
    <p
      class="
        py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
      "
      id="notice"
    ><%= notice %></p>
  <% end %>

  <div id="applications" class="min-w-full">
    <% if @applications.any? %>
      <ul role="list" class="divide-y divide-gray-100">
        <% @applications.each do |application| %>
          <li class="flex items-center justify-between gap-x-6 py-5">
            <div class="min-w-0">
              <div class="flex items-start gap-x-3">
                <p class="text-sm/6 font-semibold text-gray-900"><%= application.position %></p>
                <p
                  class="
                    mt-0.5 whitespace-nowrap rounded-md bg-green-50 px-1.5 py-0.5 text-xs
                    font-medium text-green-700 ring-1 ring-inset ring-green-600/20
                  "
                ><%= application.status %></p>
              </div>
              <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                <p class="whitespace-nowrap">Created at
                  <time datetime="2023-03-17T00:00Z"><%= application.created_at %></time></p>
                <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                  <circle cx="1" cy="1" r="1"/>
                </svg>
                <p class="truncate"><%= application.company %></p>
              </div>
            </div>
            <div class="flex flex-none items-center gap-x-4" data-controller="menu">
              <%= link_to "View Application",
              application,
              class:
                "hidden rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:block" %>
              <div class="relative flex-none">
                <button
                  data-menu-target="button"
                  data-action="click->menu#toggleMenu"
                  id="options-menu-<%=application.id%>-button"
                  type="button"
                  class="-m-2.5 block p-2.5 text-gray-500 hover:text-gray-900"
                  aria-expanded="false"
                  aria-haspopup="true"
                >
                  <span class="sr-only">Open options</span>
                  <svg
                    class="size-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    aria-hidden="true"
                    data-slot="icon"
                  >
                    <path
                      d="M10 3a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM10 8.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM11.5 15.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z"
                    />
                  </svg>
                </button>
                <div
                  data-menu-target="menu"
                  class="
                    transition opacity-0 scale-95 pointer-events-none absolute right-0 z-10 mt-2
                    w-32 origin-top-right rounded-md bg-white py-2 shadow-lg ring-1 ring-gray-900/5
                    focus:outline-none
                  "
                  role="menu"
                  aria-orientation="vertical"
                  aria-labelledby="options-menu-<%=application.id%>-button"
                  tabindex="-1"
                >
                  <%= link_to "View",
                  application,
                  class: "block sm:hidden px-3 py-1 text-sm/6 text-gray-900",
                  role: "menuitem",
                  id: "options-menu-#{application.id}-item-0",
                  tabindex: "-1" %>
                  <%= link_to "Edit",
                  edit_application_path(application),
                  class: "block px-3 py-1 text-sm/6 text-gray-900",
                  role: "menuitem",
                  id: "options-menu-#{application.id}-item-1",
                  tabindex: "-1" %>
                  <%= button_to "Delete",
                  application,
                  method: :delete,
                  class: "block px-3 py-1 text-sm/6 text-gray-900",
                  role: "menuitem",
                  id: "options-menu-#{application.id}-item-2",
                  tabindex: "-1" %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-black">No applications yet!
        <%= link_to "Go add one!",
        new_application_path,
        { class: "text-indigo-400 hover:text-indigo-500 hover:underline" } %></p>
    <% end %>
  </div>
</div>

app/views/applications/new.html.erb
<% content_for :header do %>
  <h1 class="text-3xl font-bold tracking-tight text-white">Applications</h1>
  <%= link_to "Back to applications",
  applications_path,
  class:
    "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-black" %>
<% end %>

<%= render "form", application: @application %>

app/views/applications/show.html.erb
<% content_for :header do %>
  <div>
    <h1 class="text-3xl font-bold tracking-tight text-white"><%= @application.position %></h1>
    <p class="text-white/80"><%= @application.company %></p>
  </div>
  <div class="flex gap-4 items-center">
    <%= link_to "Back to applications",
    applications_path,
    class:
      "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-black" %>
  </div>
<% end %>

<% content_for :title do %>
  Applications |
  <%= @application.position %>
<% end %>

<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p
        class="
          py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block
        "
        id="notice"
      ><%= notice %></p>
    <% end %>

    <%= render @application %>
  </div>
</div>