config/routes.rb
Rails.application.routes.draw do
  post "job_scraper/scrape", to: "job_scraper#scrape", as: :scrape_job
  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create, :destroy]
  resources :passwords, param: :token
  resources :applications
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "applications#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100 dark:bg-gray-900 dark:text-gray-100">
  <head>
    <title><%= content_for(:title) || "Applify" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">

    <div class="min-h-full">
      <div class="bg-gray-800 pb-32" data-controller="header">
        <nav class="bg-gray-800">
          <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="border-b border-gray-700">
              <div class="flex h-16 items-center justify-between px-4 sm:px-0">
                <div class="flex items-center">
                  <div class="shrink-0">
                    <img
                      class="size-8"
                      src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500"
                      alt="Your Company"
                    >
                  </div>
                  <div class="hidden md:block">
                    <div class="ml-10 flex items-baseline space-x-4">
                      <!-- Current: "bg-gray-900 text-white", Default:
                      "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                      <a
                        href="#"
                        class="
                          rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white
                        "
                        aria-current="page"
                      >Dashboard</a>
                      <a
                        href="#"
                        class="
                          rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700
                          hover:text-white
                        "
                      >Team</a>
                      <a
                        href="#"
                        class="
                          rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700
                          hover:text-white
                        "
                      >Projects</a>
                      <a
                        href="#"
                        class="
                          rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700
                          hover:text-white
                        "
                      >Calendar</a>
                      <a
                        href="#"
                        class="
                          rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700
                          hover:text-white
                        "
                      >Reports</a>
                    </div>
                  </div>
                </div>
                <% if authenticated? %>
                  <div class="hidden md:block">
                    <div class="ml-4 flex items-center md:ml-6">
                      <!-- Profile dropdown -->
                      <div class="relative ml-3" data-controller="menu">
                        <button
                          data-action="click->menu#toggleMenu"
                          data-menu-target="button"
                          type="button"
                          class="
                            relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm
                            focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2
                            focus:ring-offset-gray-800
                          "
                          id="user-menu-button"
                          aria-expanded="false"
                          aria-haspopup="true"
                        >
                          <span class="absolute -inset-1.5"></span>
                          <span class="sr-only">Open user menu</span>
                          <img
                            class="size-8 rounded-full"
                            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                            alt=""
                          >
                        </button>

                        <div
                          data-menu-target="menu"
                          class="
                            transition absolute opacity-0 scale-95 pointer-events-none right-0 z-10 mt-2
                            w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black/5
                            focus:outline-none
                          "
                          role="menu"
                          aria-orientation="vertical"
                          aria-labelledby="user-menu-button"
                          tabindex="-1"
                        >
                          <a
                            href="#"
                            class="block px-4 py-2 text-sm text-gray-700"
                            role="menuitem"
                            tabindex="-1"
                            id="user-menu-item-0"
                          >Your Profile</a>
                          <a
                            href="#"
                            class="block px-4 py-2 text-sm text-gray-700"
                            role="menuitem"
                            tabindex="-1"
                            id="user-menu-item-1"
                          >Settings</a>
                          <%= button_to "Sign out",
                          session_path,
                          class: "px-4 py-2 rounded bg-indigo-700 text-white hover:bg-indigo-600",
                          method: :delete %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="-mr-2 flex md:hidden">
                  <!-- Mobile menu button -->
                  <button
                    data-action="click->header#toggleMenu"
                    type="button"
                    class="
                      relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2
                      text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2
                      focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800
                    "
                    aria-controls="mobile-menu"
                    aria-expanded="false"
                  >
                    <span class="absolute -inset-0.5"></span>
                    <span class="sr-only">Open main menu</span>
                    <!-- Menu open: "hidden", Menu closed: "block" -->
                    <svg
                      data-header-target="show-menu"
                      class="block size-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      aria-hidden="true"
                      data-slot="icon"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                      />
                    </svg>
                    <!-- Menu open: "block", Menu closed: "hidden" -->
                    <svg
                      data-header-target="hide-menu"
                      class="hidden size-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      aria-hidden="true"
                      data-slot="icon"
                    >
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"/>
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- Mobile menu, show/hide based on menu state. -->
          <div
            class="border-b border-gray-700 hidden"
            id="mobile-menu"
            data-header-target="mobile-menu"
          >
            <div class="space-y-1 px-2 py-3 sm:px-3">
              <a
                href="#"
                class="
                  block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white
                "
                aria-current="page"
              >Dashboard</a>
              <a
                href="#"
                class="
                  block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700
                  hover:text-white
                "
              >Team</a>
              <a
                href="#"
                class="
                  block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700
                  hover:text-white
                "
              >Projects</a>
              <a
                href="#"
                class="
                  block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700
                  hover:text-white
                "
              >Calendar</a>
              <a
                href="#"
                class="
                  block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700
                  hover:text-white
                "
              >Reports</a>
            </div>
            <% if authenticated? %>
              <div class="border-t border-gray-700 pb-3 pt-4">
                <div class="flex items-center px-5">
                  <div class="text-base/5 font-medium text-white"><%= Current.user.email_address %></div>
                </div>
                <div class="mt-3 space-y-1 px-2">
                  <%= link_to "Profile",
                  "/userid",
                  class:
                    "block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white" %>
                  button_to "Sign out", session_path, class: "px-4 py-2 rounded
                  bg-indigo-700 text-white hover:bg-indigo-600", method:
                  :delete
                </div>
              </div>
            <% end %>
          </div>
        </nav>
        <header class="py-10">
          <div
            class="
              mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 flex justify-between items-center
            "
          >
            <%= yield :header %>
          </div>
        </header>
      </div>

      <main class="-mt-32">
        <div class="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8">
          <div class="rounded-lg bg-white px-5 py-6 shadow sm:px-6"><%= yield %></div>
        </div>
      </main>
    </div>
  </body>
</html>